//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Character : GameObject
{
	private Double maxSpeed
	{
		get
        {
            return maxSpeed;
        }
		set
        {
            maxSpeed = value;
        }
	}

	private bool dead
	{
		get
        {
            return dead;
        }
		set
        {
            dead = value;
        }
	}

	private Double jumpHeight
	{
		get
        {
            return jumpHeight;
        }
		set
        {
            jumpHeight = value;
        }
	}

	private Double acceleration
	{
		get
        {
            return acceleration;
        }
		set
        {
            acceleration = value;
        }
	}


	public virtual void changeSpeed()
	{
		throw new System.NotImplementedException();
	}

	public Character(Image image, PointF point)
	{
	}

}

