//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Character : GameObject
{
	private int maxSpeed
	{
		get;
		set;
	}

	private bool dead
	{
		get;
		set;
	}

	private int jumpHeight
	{
		get;
		set;
	}

	private int currentSpeed
	{
		get;
		set;
	}

	public Character(Image image, PointF point)
	{
	}

	public virtual void changeSpeed(int speed)
	{
		throw new System.NotImplementedException();
	}

}

