//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Character : GameObject
{
	private Double maxSpeed
	{
		get;
		set;
	}

	private bool dead
	{
		get;
		set;
	}

	private Double jumpHeight
	{
		get;
		set;
	}

	private int currentSpeed
	{
		get;
		set;
	}

	public Character(Image image, int x, int y)
	{
	}

	public virtual void changeSpeed(int speed)
	{
		throw new System.NotImplementedException();
        this.currentSpeed = currentSpeed + speed;
	}

}

