//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Clock
{
	private int time
	{
		get;
		set;
	}

	private Thread thread
	{
		get;
		set;
	}

	private bool stopThread
	{
		get;
		set;
	}

	public virtual void startClock()
	{
		throw new System.NotImplementedException();
	}

	public virtual void stopClock()
	{
		throw new System.NotImplementedException();
	}

	public Clock()
	{
	}

	private void incrementTime()
	{
		throw new System.NotImplementedException();
	}

}

