//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameObject
{
	private Image image
	{
        get
        {
            return image;
        }
		set
        {
            image = value;
        }
	}

	private PointF point
	{
		get
        {
            return point;
        }
		set
        {
            point = value;
        }
	}

	private bool visible
	{
		get
        {
            return visible;
        }
		set
        {
            visible = value;
        }
	}

	private bool collison
	{
		get
        {
            return collison;
        }
		set
        {
            collison = value;
        }
	}

	public virtual void Shape(PointF point, Image image, bool collison, bool visible)
	{
		throw new System.NotImplementedException();
	}

}

