//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameObject
{
	private Image image
	{
		get;
		set;
	}

	private PointF point
	{
		get;
		set;
	}

	private bool visible
	{
		get;
		set;
	}

	private bool collison
	{
		get;
		set;
	}

	public virtual void Image()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Visible()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Shape(PointF point, Image image, bool collison, bool visible)
	{
		throw new System.NotImplementedException();
	}

}

