//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LevelEditor
{
	public virtual Level level
	{
		get;
		set;
	}

	public virtual Game game
	{
		get;
		set;
	}

	public virtual Level Level
	{
		get;
		set;
	}

	public virtual Game Game
	{
		get;
		set;
	}

	public virtual bool validateLevel()
	{
		throw new System.NotImplementedException();
	}

	public virtual void updateLevel()
	{
		throw new System.NotImplementedException();
	}

	public virtual void exit()
	{
		throw new System.NotImplementedException();
	}

	public LevelEditor(Level level)
	{
	}

}

