//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PressurePlate : GameObject
{
	private GameObject affectedShape
	{
		get
        {
            return affectedShape;
        }
		set
        {
            affectedShape = value;
        }
	}

	public virtual void activate()
	{
		throw new System.NotImplementedException();
	}

	public PressurePlate(GameObject affected, PointF point)
	{
	}

}

