//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PressurePlate : GameObject
{
	private GameObject affectedShape
	{
		get;
		set;
	}

    private int verticalChange
    {
        get;
        set;
    }

    private int horizontalChange
    {
        get;
        set;
    }

	public virtual void activate()
	{
		throw new System.NotImplementedException();
        affectedShape.y = y + verticalChange;
        affectedShape.x = x + horizontalChange;
	}

	public PressurePlate(GameObject affected, int x, int y)
	{
        affected.y = y + verticalChange;
        affected.x = x + horizontalChange;
	}

}

