//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

public class Clock
{
	public int time
	{
		get;
		set;
	}

	private Thread thread
	{
		get;
		set;
	}

	public virtual void startClock()
	{
		
	}

	public virtual void stopClock()
	{
		throw new System.NotImplementedException();
	}

	public Clock()
	{
	}

}

