//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Game
{
	private Level level
	{
		get;
		set;
	}

	private MediaPlayer mediaplayer
	{
		get;
		set;
	}

	private Timer thread
	{
		get;
		set;
	}

	private bool testing
	{
		get;
		set;
	}

	private Graphics graphics
	{
		get;
		set;
	}

	public virtual Level Level
	{
		get;
		set;
	}

	public virtual void play()
	{
		throw new System.NotImplementedException();
	}

	public Game(Level level, bool testing)
	{
	}

	private bool checkForEnd()
	{
		throw new System.NotImplementedException();
	}

	public virtual void return()
	{
		throw new System.NotImplementedException();
	}

	private bool validateNextPosition()
	{
		throw new System.NotImplementedException();
	}

	private bool checkForCollison()
	{
		throw new System.NotImplementedException();
	}

	private bool checkForSpike()
	{
		throw new System.NotImplementedException();
	}

	private bool checkForPressurePlate()
	{
		throw new System.NotImplementedException();
	}

	private void render()
	{
		throw new System.NotImplementedException();
	}

	private void endSequence()
	{
		throw new System.NotImplementedException();
	}

	private void update()
	{
		throw new System.NotImplementedException();
	}

}

