//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

public class GameObject
{
	protected Image image
	{
		get;
		set;
	}

	public PointF point
	{
		get;
		set;
	}

	private bool visible
	{
		get;
		set;
	}

	public bool collision
	{
		get;
		set;
	}

	public virtual void Shape(PointF point, Image image, bool collision, bool visible)
	{
        this.point = point;
        this.image = image;
        this.collision = collision;
        this.visible = visible;
	}

}

