//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.IO;

public class Level
{
    public Character character
    {
        get;
        set;
    }
    private string filename
	{
		get;
		set;
	}

	private IEnumerable<string> soundEffets
	{
		get;
		set;
	}

	private IEnumerable<GameObject> layout
	{
		get;
		set;
	}

	private Clock timer
	{
		get;
		set;
	}

	public virtual Clock clock
	{
		get;
		set;
	}

	public virtual IEnumerable<GameObject> loadLevel()
	{
        try
        {
            using (StreamReader sr = new StreamReader(this.filename))
            {
                String line = sr.ReadToEnd();
                //DrawImage, probably going to need to do serialization 
            }
        }
        catch (Exception e)
        {
            Console.WriteLine("The file could not be read:");
            Console.WriteLine(e.Message);
        }
    }

	public virtual bool saveLevel()
	{
		throw new System.NotImplementedException();
	}

	private bool levelExisit()
	{
		throw new System.NotImplementedException();
	}

	public virtual IEnumerable<int> checkLocation(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public Level(string filename)
	{
        this.filename = filename;
        layout = loadLevel();
        foreach (GameObject gameObject in layout)
        {
            if(gameObject is Character)
            {
                character = (Character)gameObject;
                break;
            }
        }
        clock = new Clock();
	}

	private bool checkReadOnly()
	{
		throw new System.NotImplementedException();
	}

	public virtual IEnumerable<GameObject> shapesAroundCharacter()
	{
		throw new System.NotImplementedException();
	}

	public virtual GameObject shapeAt(PointF point)
	{
        foreach (GameObject gameObject in layout)
        {
            if(gameObject.point == point)
            {
                return gameObject;
            }
        }
        return null;
	}

}

