//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

public class PressurePlate : GameObject
{
	public GameObject affectedShape
	{
		get;
		set;
	}

    public int verticalChange
    {
        get;
        set;
    }

    public int horizontalChange
    {
        get;
        set;
    }

	public virtual void activate()
	{
        affectedShape.point.X = point.X + horizontalChange;
        affectedShape.point.Y = point.Y + verticalChange;
	}

	public PressurePlate(GameObject affected, PointF point)
	{
        affectedShape = affected;
        this.point = point;
	}

}

