//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Spike : GameObject
{
	public virtual void killPlayer()
	{
		throw new System.NotImplementedException();
	}

	public Spike(pointF point)
	{
	}

}

